name: Doc update on release

on:
  workflow_dispatch

jobs:
  triggerWorkflowDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: Luckenborg/doc_content_target
          event-type: update-openhabian-docs-event