name: Doc update on release
description: Will trigger an update of the docs repository on release of this one

on:
  workflow_dispatch

jobs:
  triggerWorkflowDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              'Luckenborg',
              'doc_content_target',
              'workflows/fetch_docs_openhabian.yml',
              'main',
            });